language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - pep8 --ignore=E501 rtkit || return 1
  - pyflakes -x W rtkit || return 1
  - py.test --doctest-modules rtkit -v